import { describe, it, expect, beforeAll, beforeEach, afterEach } from "vitest";
import { mockClient } from "aws-sdk-client-mock";
import {
  S3Client,
  PutObjectCommand,
  GetObjectCommand,
  DeleteObjectCommand,
} from "@aws-sdk/client-s3";
import {
  GET as listDocsRoute,
  POST as createDocRoute,
} from "@/app/api/deals/[id]/documents/route";
import { POST as uploadUrlRoute } from "@/app/api/deals/[id]/documents/upload-url/route";
import { GET as downloadUrlRoute } from "@/app/api/documents/[id]/download-url/route";
import { DELETE as deleteDocRoute } from "@/app/api/documents/[id]/route";
import { setVerifyOptionsForTesting } from "@/lib/auth";
import { setS3ClientForTesting } from "@/lib/s3";
import { prisma } from "@/lib/db";
import { authHeader, getTestSigner } from "../helpers/jwt";
import { truncateAll } from "../helpers/db";
import { createUser, createDeal } from "../helpers/factories";

const s3Mock = mockClient(S3Client);

beforeAll(async () => {
  const { verifyOpts } = await getTestSigner();
  setVerifyOptionsForTesting(verifyOpts);

  // Use a real S3Client (only needed for the local SDK signer to compute URLs)
  // with fake credentials. We mock the underlying HTTP send for delete; PUT/GET
  // URLs are generated by the local signer and never actually call S3.
  const client = new S3Client({
    region: "us-east-1",
    credentials: { accessKeyId: "test", secretAccessKey: "test" },
  });
  setS3ClientForTesting(client, "test-bucket");
});

beforeEach(async () => {
  await truncateAll();
  s3Mock.reset();
  s3Mock.on(DeleteObjectCommand).resolves({});
  s3Mock.on(PutObjectCommand).resolves({});
  s3Mock.on(GetObjectCommand).resolves({});
});

afterEach(() => {
  s3Mock.reset();
});

function ctx(id: string) {
  return { params: Promise.resolve({ id }) };
}

describe("POST /api/deals/[id]/documents/upload-url", () => {
  it("returns a pre-signed PUT url and a deal-scoped key", async () => {
    const agent = await createUser({ role: "agent", auth0_id: "auth0|a" });
    const deal = await createDeal({ agent_id: agent.id });
    const req = new Request(
      `http://localhost/api/deals/${deal.id}/documents/upload-url`,
      {
        method: "POST",
        headers: {
          "content-type": "application/json",
          authorization: await authHeader("auth0|a", ["agent"]),
        },
        body: JSON.stringify({
          file_name: "contract.pdf",
          mime_type: "application/pdf",
        }),
      }
    );
    const res = await uploadUrlRoute(req, ctx(deal.id));
    expect(res.status).toBe(200);
    const body = (await res.json()) as { upload_url: string; s3_key: string };
    expect(body.upload_url).toMatch(/^https:\/\/.*\.s3\..+\.amazonaws\.com\//);
    expect(body.s3_key).toMatch(new RegExp(`^deals/${deal.id}/\\d+/contract\\.pdf$`));
  });

  it("400 when file_name missing", async () => {
    const agent = await createUser({ role: "agent", auth0_id: "auth0|a" });
    const deal = await createDeal({ agent_id: agent.id });
    const req = new Request(
      `http://localhost/api/deals/${deal.id}/documents/upload-url`,
      {
        method: "POST",
        headers: {
          "content-type": "application/json",
          authorization: await authHeader("auth0|a", ["agent"]),
        },
        body: JSON.stringify({}),
      }
    );
    const res = await uploadUrlRoute(req, ctx(deal.id));
    expect(res.status).toBe(400);
  });

  it("lets a deal participant (buyer) request a pre-signed url", async () => {
    const agent = await createUser({ role: "agent", auth0_id: "auth0|a" });
    const buyer = await createUser({ role: "buyer", auth0_id: "auth0|b" });
    const deal = await createDeal({ agent_id: agent.id });
    await prisma.deal_participants.create({
      data: { deal_id: deal.id, user_id: buyer.id, role: "buyer" },
    });
    const req = new Request(
      `http://localhost/api/deals/${deal.id}/documents/upload-url`,
      {
        method: "POST",
        headers: {
          "content-type": "application/json",
          authorization: await authHeader("auth0|b", ["buyer"]),
        },
        body: JSON.stringify({
          file_name: "preapproval.pdf",
          mime_type: "application/pdf",
        }),
      }
    );
    const res = await uploadUrlRoute(req, ctx(deal.id));
    expect(res.status).toBe(200);
    const body = (await res.json()) as { upload_url: string; s3_key: string };
    expect(body.upload_url).toMatch(/^https:\/\/.*\.s3\..+\.amazonaws\.com\//);
    expect(body.s3_key).toMatch(
      new RegExp(`^deals/${deal.id}/\\d+/preapproval\\.pdf$`)
    );
  });

  it("404 when caller is neither the agent nor a participant", async () => {
    const agent = await createUser({ role: "agent" });
    const stranger = await createUser({ role: "agent", auth0_id: "auth0|other" });
    const deal = await createDeal({ agent_id: agent.id });
    void stranger;
    const req = new Request(
      `http://localhost/api/deals/${deal.id}/documents/upload-url`,
      {
        method: "POST",
        headers: {
          "content-type": "application/json",
          authorization: await authHeader("auth0|other", ["agent"]),
        },
        body: JSON.stringify({ file_name: "x.pdf" }),
      }
    );
    const res = await uploadUrlRoute(req, ctx(deal.id));
    expect(res.status).toBe(404);
  });
});

describe("POST /api/deals/[id]/documents", () => {
  it("creates a document record with uploader info", async () => {
    const agent = await createUser({
      role: "agent",
      auth0_id: "auth0|a",
      name: "Agent A",
    });
    const deal = await createDeal({ agent_id: agent.id });
    const req = new Request(`http://localhost/api/deals/${deal.id}/documents`, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        authorization: await authHeader("auth0|a", ["agent"]),
      },
      body: JSON.stringify({
        name: "contract.pdf",
        s3_key: `deals/${deal.id}/123/contract.pdf`,
        mime_type: "application/pdf",
        file_size: 12345,
      }),
    });
    const res = await createDocRoute(req, ctx(deal.id));
    expect(res.status).toBe(201);
    const body = (await res.json()) as {
      name: string;
      uploader_name: string;
      file_size: number;
    };
    expect(body.name).toBe("contract.pdf");
    expect(body.uploader_name).toBe("Agent A");
    expect(body.file_size).toBe(12345);
  });

  it("400 when name or s3_key missing", async () => {
    const agent = await createUser({ role: "agent", auth0_id: "auth0|a" });
    const deal = await createDeal({ agent_id: agent.id });
    const req = new Request(`http://localhost/api/deals/${deal.id}/documents`, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        authorization: await authHeader("auth0|a", ["agent"]),
      },
      body: JSON.stringify({ name: "x" }),
    });
    const res = await createDocRoute(req, ctx(deal.id));
    expect(res.status).toBe(400);
  });

  it("lets a deal participant (buyer) confirm an upload (uploaded_by = buyer)", async () => {
    const agent = await createUser({ role: "agent", auth0_id: "auth0|a" });
    const buyer = await createUser({
      role: "buyer",
      auth0_id: "auth0|b",
      name: "Bob Buyer",
    });
    const deal = await createDeal({ agent_id: agent.id });
    await prisma.deal_participants.create({
      data: { deal_id: deal.id, user_id: buyer.id, role: "buyer" },
    });
    const req = new Request(`http://localhost/api/deals/${deal.id}/documents`, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        authorization: await authHeader("auth0|b", ["buyer"]),
      },
      body: JSON.stringify({
        name: "preapproval.pdf",
        s3_key: `deals/${deal.id}/123/preapproval.pdf`,
        mime_type: "application/pdf",
        file_size: 4321,
      }),
    });
    const res = await createDocRoute(req, ctx(deal.id));
    expect(res.status).toBe(201);
    const body = (await res.json()) as {
      name: string;
      uploaded_by: string;
      uploader_name: string;
    };
    expect(body.name).toBe("preapproval.pdf");
    expect(body.uploaded_by).toBe(buyer.id);
    expect(body.uploader_name).toBe("Bob Buyer");
  });

  it("404 when caller is neither the agent nor a participant", async () => {
    const agent = await createUser({ role: "agent" });
    const stranger = await createUser({ role: "agent", auth0_id: "auth0|other" });
    const deal = await createDeal({ agent_id: agent.id });
    void stranger;
    const req = new Request(`http://localhost/api/deals/${deal.id}/documents`, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        authorization: await authHeader("auth0|other", ["agent"]),
      },
      body: JSON.stringify({
        name: "x.pdf",
        s3_key: "k",
      }),
    });
    const res = await createDocRoute(req, ctx(deal.id));
    expect(res.status).toBe(404);
  });
});

describe("GET /api/deals/[id]/documents", () => {
  it("agent and participant can list documents", async () => {
    const agent = await createUser({ role: "agent", auth0_id: "auth0|a" });
    const buyer = await createUser({ role: "buyer", auth0_id: "auth0|b" });
    const deal = await createDeal({ agent_id: agent.id });
    await prisma.deal_participants.create({
      data: { deal_id: deal.id, user_id: buyer.id, role: "buyer" },
    });
    await prisma.documents.create({
      data: {
        deal_id: deal.id,
        uploaded_by: agent.id,
        name: "doc.pdf",
        s3_key: "k",
      },
    });
    const req = new Request(`http://localhost/api/deals/${deal.id}/documents`, {
      headers: { authorization: await authHeader("auth0|b", ["buyer"]) },
    });
    const res = await listDocsRoute(req, ctx(deal.id));
    expect(res.status).toBe(200);
    const body = (await res.json()) as { name: string }[];
    expect(body.length).toBe(1);
    expect(body[0].name).toBe("doc.pdf");
  });
});

describe("GET /api/documents/[id]/download-url", () => {
  it("returns a pre-signed GET url for an accessible document", async () => {
    const agent = await createUser({ role: "agent", auth0_id: "auth0|a" });
    const deal = await createDeal({ agent_id: agent.id });
    const doc = await prisma.documents.create({
      data: {
        deal_id: deal.id,
        uploaded_by: agent.id,
        name: "x.pdf",
        s3_key: "deals/abc/123/x.pdf",
      },
    });
    const req = new Request(
      `http://localhost/api/documents/${doc.id}/download-url`,
      { headers: { authorization: await authHeader("auth0|a", ["agent"]) } }
    );
    const res = await downloadUrlRoute(req, ctx(doc.id));
    expect(res.status).toBe(200);
    const body = (await res.json()) as { download_url: string };
    expect(body.download_url).toMatch(/^https:\/\/.*amazonaws\.com\//);
  });

  it("404 for unrelated user", async () => {
    const agent = await createUser({ role: "agent" });
    const stranger = await createUser({ role: "buyer", auth0_id: "auth0|s" });
    const deal = await createDeal({ agent_id: agent.id });
    void stranger;
    const doc = await prisma.documents.create({
      data: {
        deal_id: deal.id,
        uploaded_by: agent.id,
        name: "x.pdf",
        s3_key: "k",
      },
    });
    const req = new Request(
      `http://localhost/api/documents/${doc.id}/download-url`,
      { headers: { authorization: await authHeader("auth0|s", ["buyer"]) } }
    );
    const res = await downloadUrlRoute(req, ctx(doc.id));
    expect(res.status).toBe(404);
  });
});

describe("DELETE /api/documents/[id]", () => {
  it("agent owner can delete; record gone, S3 delete attempted", async () => {
    const agent = await createUser({ role: "agent", auth0_id: "auth0|a" });
    const deal = await createDeal({ agent_id: agent.id });
    const doc = await prisma.documents.create({
      data: {
        deal_id: deal.id,
        uploaded_by: agent.id,
        name: "x.pdf",
        s3_key: "k",
      },
    });
    const req = new Request(`http://localhost/api/documents/${doc.id}`, {
      method: "DELETE",
      headers: { authorization: await authHeader("auth0|a", ["agent"]) },
    });
    const res = await deleteDocRoute(req, ctx(doc.id));
    expect(res.status).toBe(204);

    const row = await prisma.documents.findUnique({ where: { id: doc.id } });
    expect(row).toBeNull();
    // deleteObject is awaited by the route, so the S3 call is deterministic
    // by the time the response resolves — no race.
    const calls = s3Mock.commandCalls(DeleteObjectCommand);
    expect(calls.length).toBe(1);
    expect(calls[0].args[0].input.Key).toBe("k");
  });

  it("still 204s and deletes the row when the S3 delete throws", async () => {
    const agent = await createUser({ role: "agent", auth0_id: "auth0|a" });
    const deal = await createDeal({ agent_id: agent.id });
    const doc = await prisma.documents.create({
      data: {
        deal_id: deal.id,
        uploaded_by: agent.id,
        name: "x.pdf",
        s3_key: "k",
      },
    });
    s3Mock.on(DeleteObjectCommand).rejects(new Error("s3 down"));
    const req = new Request(`http://localhost/api/documents/${doc.id}`, {
      method: "DELETE",
      headers: { authorization: await authHeader("auth0|a", ["agent"]) },
    });
    const res = await deleteDocRoute(req, ctx(doc.id));
    expect(res.status).toBe(204);
    const row = await prisma.documents.findUnique({ where: { id: doc.id } });
    expect(row).toBeNull();
  });

  it("404 when caller is not the owning agent", async () => {
    const agent = await createUser({ role: "agent" });
    const stranger = await createUser({ role: "agent", auth0_id: "auth0|s" });
    const deal = await createDeal({ agent_id: agent.id });
    void stranger;
    const doc = await prisma.documents.create({
      data: {
        deal_id: deal.id,
        uploaded_by: agent.id,
        name: "x.pdf",
        s3_key: "k",
      },
    });
    const req = new Request(`http://localhost/api/documents/${doc.id}`, {
      method: "DELETE",
      headers: { authorization: await authHeader("auth0|s", ["agent"]) },
    });
    const res = await deleteDocRoute(req, ctx(doc.id));
    expect(res.status).toBe(404);
  });
});
