import { PERMISSIONS, Permission } from './permissions';

export type PermissionGroup = {
  id: string;
  name: string;
  description: string;
  permissions: Permission[];
};

export type GroupId = 'agent' | 'buyer' | 'seller' | 'admin' | 'tc';

// ─────────────────────────────────────────────────────────────────────────────
// BUYER
// View-first. Acts on their own deal, completes tasks, signs docs, tracks
// contingencies and earnest money, enrolls in Fast Pass, wires closing funds.
// ─────────────────────────────────────────────────────────────────────────────
const BUYER_PERMISSIONS: Permission[] = [
  // DEAL
  PERMISSIONS.DEAL_VIEW,

  // STAGE
  PERMISSIONS.STAGE_VIEW_REQUIREMENTS,
  PERMISSIONS.STAGE_VIEW_HISTORY,

  // CONTINGENCY
  PERMISSIONS.CONTINGENCY_VIEW,

  // EARNEST MONEY
  PERMISSIONS.EARNEST_MONEY_VIEW_STATUS,

  // DISCLOSURE — buyers receive and acknowledge disclosures
  PERMISSIONS.DISCLOSURE_VIEW,
  PERMISSIONS.DISCLOSURE_VIEW_STATUS,
  PERMISSIONS.DISCLOSURE_ACKNOWLEDGE,

  // TASK
  PERMISSIONS.TASK_VIEW,
  PERMISSIONS.TASK_COMPLETE,

  // MESSAGE
  PERMISSIONS.MESSAGE_VIEW,
  PERMISSIONS.MESSAGE_SEND,
  PERMISSIONS.MESSAGE_EDIT_OWN,
  PERMISSIONS.MESSAGE_USE_TEMPLATES,

  // DOCUMENT
  PERMISSIONS.DOCUMENT_VIEW,
  PERMISSIONS.DOCUMENT_UPLOAD,
  PERMISSIONS.DOCUMENT_DOWNLOAD,
  PERMISSIONS.DOCUMENT_SIGN,
  PERMISSIONS.DOCUMENT_MARK_RECEIVED,

  // ESIGN
  PERMISSIONS.ESIGN_VIEW_STATUS,
  PERMISSIONS.ESIGN_DOWNLOAD_CERTIFICATE,

  // PROPERTY
  PERMISSIONS.PROPERTY_VIEW,
  PERMISSIONS.PROPERTY_ADD,         // wishlist / candidate properties

  // SHOWING
  PERMISSIONS.SHOWING_VIEW,
  PERMISSIONS.SHOWING_REQUEST,
  PERMISSIONS.SHOWING_CANCEL,

  // OFFER
  PERMISSIONS.OFFER_VIEW,
  PERMISSIONS.OFFER_VIEW_ANALYSIS_DETAILS,

  // APPRAISAL — buyers have legal right to receive appraisal (ECOA)
  PERMISSIONS.APPRAISAL_VIEW_RESULT,
  PERMISSIONS.APPRAISAL_VIEW_REPORT,

  // EVENT
  PERMISSIONS.EVENT_VIEW,
  PERMISSIONS.EVENT_RESPOND,
  PERMISSIONS.EVENT_VIEW_AVAILABILITY,

  // LENDING
  PERMISSIONS.LENDING_VIEW_STATUS,
  PERMISSIONS.LENDING_VIEW_MILESTONES,
  PERMISSIONS.LENDING_VIEW_DISCLOSURES,

  // CLOSING — buyers wire funds and review settlement statement
  PERMISSIONS.CLOSING_VIEW_WIRE_INSTRUCTIONS,
  PERMISSIONS.CLOSING_APPROVE_ALTA,

  // POST-CLOSE — buyers track deed recording and title policy delivery
  PERMISSIONS.POST_CLOSE_CONFIRM_RECORDING,
  PERMISSIONS.POST_CLOSE_TRACK_TITLE_POLICY,

  // FASTPASS
  PERMISSIONS.FASTPASS_VIEW,
  PERMISSIONS.FASTPASS_ENROLL,

  // PORTAL
  PERMISSIONS.PORTAL_VIEW,

  // NOTIFICATION
  PERMISSIONS.NOTIFICATION_RECEIVE,
  PERMISSIONS.NOTIFICATION_MANAGE,

  // BILLING
  PERMISSIONS.BILLING_VIEW,
  PERMISSIONS.BILLING_DOWNLOAD_INVOICE,
  PERMISSIONS.BILLING_MANAGE_PAYMENT_METHOD,

  // SEARCH
  PERMISSIONS.SEARCH_DEALS,

  // DASHBOARD
  PERMISSIONS.DASHBOARD_VIEW,

  // TEMPLATE
  PERMISSIONS.TEMPLATE_USE,
];

// ─────────────────────────────────────────────────────────────────────────────
// SELLER
// Listing-aware. Creates and delivers disclosures, acts on offers, reviews
// listing performance, tracks contingency deadlines, approves ALTA at closing.
// ─────────────────────────────────────────────────────────────────────────────
const SELLER_PERMISSIONS: Permission[] = [
  // DEAL
  PERMISSIONS.DEAL_VIEW,

  // STAGE
  PERMISSIONS.STAGE_VIEW_REQUIREMENTS,
  PERMISSIONS.STAGE_VIEW_HISTORY,

  // CONTINGENCY — sellers track buyer contingency deadlines too
  PERMISSIONS.CONTINGENCY_VIEW,

  // DISCLOSURE — sellers create and deliver their disclosure package
  PERMISSIONS.DISCLOSURE_VIEW,
  PERMISSIONS.DISCLOSURE_VIEW_STATUS,
  PERMISSIONS.DISCLOSURE_CREATE,
  PERMISSIONS.DISCLOSURE_SEND,

  // TASK
  PERMISSIONS.TASK_VIEW,
  PERMISSIONS.TASK_COMPLETE,

  // MESSAGE
  PERMISSIONS.MESSAGE_VIEW,
  PERMISSIONS.MESSAGE_SEND,
  PERMISSIONS.MESSAGE_EDIT_OWN,
  PERMISSIONS.MESSAGE_USE_TEMPLATES,

  // DOCUMENT
  PERMISSIONS.DOCUMENT_VIEW,
  PERMISSIONS.DOCUMENT_UPLOAD,
  PERMISSIONS.DOCUMENT_DOWNLOAD,
  PERMISSIONS.DOCUMENT_SIGN,
  PERMISSIONS.DOCUMENT_MARK_RECEIVED,

  // ESIGN
  PERMISSIONS.ESIGN_VIEW_STATUS,
  PERMISSIONS.ESIGN_DOWNLOAD_CERTIFICATE,

  // PROPERTY
  PERMISSIONS.PROPERTY_VIEW,

  // LISTING — sellers manage their own listing content
  PERMISSIONS.LISTING_VIEW,
  PERMISSIONS.LISTING_VIEW_FEEDBACK_SUMMARY,
  PERMISSIONS.LISTING_VIEW_PERFORMANCE,
  PERMISSIONS.LISTING_EDIT,
  PERMISSIONS.LISTING_MANAGE_DESCRIPTION,
  PERMISSIONS.LISTING_MANAGE_PHOTOS,
  PERMISSIONS.LISTING_APPROVE_DRAFT,    // seller approves before listing goes live

  // SHOWING
  PERMISSIONS.SHOWING_VIEW,
  PERMISSIONS.SHOWING_FEEDBACK_VIEW,
  PERMISSIONS.SHOWING_VIEW_ACTIVITY_REPORT,

  // OFFER — sellers act on offers made to them; create net sheets to compare
  PERMISSIONS.OFFER_VIEW,
  PERMISSIONS.OFFER_ACCEPT,
  PERMISSIONS.OFFER_REJECT,
  PERMISSIONS.OFFER_COUNTER,
  PERMISSIONS.OFFER_COMPARE,
  PERMISSIONS.OFFER_VIEW_ANALYSIS_DETAILS,
  PERMISSIONS.OFFER_CREATE_NET_SHEET,

  // APPRAISAL — sellers provide access and learn the result
  PERMISSIONS.APPRAISAL_VIEW_RESULT,
  PERMISSIONS.APPRAISAL_COORDINATE_ACCESS,

  // EVENT
  PERMISSIONS.EVENT_VIEW,
  PERMISSIONS.EVENT_RESPOND,
  PERMISSIONS.EVENT_VIEW_AVAILABILITY,

  // CLOSING — sellers review and approve their side of settlement statement
  PERMISSIONS.CLOSING_APPROVE_ALTA,

  // POST-CLOSE
  PERMISSIONS.POST_CLOSE_CONFIRM_RECORDING,
  PERMISSIONS.POST_CLOSE_TRACK_TITLE_POLICY,

  // PORTAL
  PERMISSIONS.PORTAL_VIEW,

  // NOTIFICATION
  PERMISSIONS.NOTIFICATION_RECEIVE,
  PERMISSIONS.NOTIFICATION_MANAGE,

  // BILLING
  PERMISSIONS.BILLING_VIEW,
  PERMISSIONS.BILLING_DOWNLOAD_INVOICE,
  PERMISSIONS.BILLING_MANAGE_PAYMENT_METHOD,

  // SEARCH
  PERMISSIONS.SEARCH_DEALS,

  // DASHBOARD
  PERMISSIONS.DASHBOARD_VIEW,

  // TEMPLATE
  PERMISSIONS.TEMPLATE_USE,
];

// ─────────────────────────────────────────────────────────────────────────────
// AGENT
// Full deal-working access. Manages participants, advances stages, uses all AI,
// controls TC delegation and client portal, manages listings end-to-end.
// Cannot view all deals, delete deals, or modify system-level settings.
// ─────────────────────────────────────────────────────────────────────────────
const AGENT_PERMISSIONS: Permission[] = [

  // DEAL
  PERMISSIONS.DEAL_VIEW,
  PERMISSIONS.DEAL_VIEW_FINANCIALS,
  PERMISSIONS.DEAL_VIEW_SENSITIVE_DOCS,
  PERMISSIONS.DEAL_CREATE,
  PERMISSIONS.DEAL_EDIT,
  PERMISSIONS.DEAL_ADVANCE_STAGE,
  PERMISSIONS.DEAL_ARCHIVE,
  PERMISSIONS.DEAL_RESTORE_ARCHIVE,
  PERMISSIONS.DEAL_PAUSE,
  PERMISSIONS.DEAL_ASSIGN_AGENT,
  PERMISSIONS.DEAL_ADD_PARTICIPANT,
  PERMISSIONS.DEAL_REMOVE_PARTICIPANT,
  PERMISSIONS.DEAL_MANAGE_PARTICIPANTS,
  PERMISSIONS.DEAL_TRANSFER_OWNERSHIP,
  PERMISSIONS.DEAL_DELEGATE_TO_TC,
  PERMISSIONS.DEAL_CHANGE_VISIBILITY,
  PERMISSIONS.DEAL_MANAGE_PERMISSIONS,
  PERMISSIONS.DEAL_CONFIGURE_TC_ACCESS,

  // STAGE
  PERMISSIONS.STAGE_VIEW_REQUIREMENTS,
  PERMISSIONS.STAGE_VIEW_HISTORY,
  PERMISSIONS.STAGE_COMPLETE_REQUIREMENT,
  PERMISSIONS.STAGE_REOPEN,
  PERMISSIONS.STAGE_ROLLBACK,

  // DEAL — stage lifecycle actions
  PERMISSIONS.DEAL_MARK_FALLEN_THROUGH,
  PERMISSIONS.DEAL_REACTIVATE_FALLEN,

  // CONTINGENCY — agents own the contingency tracking process
  PERMISSIONS.CONTINGENCY_VIEW,
  PERMISSIONS.CONTINGENCY_TRACK,
  PERMISSIONS.CONTINGENCY_REMOVE,
  PERMISSIONS.CONTINGENCY_WAIVE,
  PERMISSIONS.CONTINGENCY_EXTEND,
  PERMISSIONS.CONTINGENCY_EXPIRE,

  // EARNEST MONEY
  PERMISSIONS.EARNEST_MONEY_VIEW_STATUS,
  PERMISSIONS.EARNEST_MONEY_CONFIRM_RECEIPT,
  PERMISSIONS.EARNEST_MONEY_RELEASE,
  PERMISSIONS.EARNEST_MONEY_DISPUTE,

  // DISCLOSURE — agents prepare, send, and track disclosures
  PERMISSIONS.DISCLOSURE_VIEW,
  PERMISSIONS.DISCLOSURE_VIEW_STATUS,
  PERMISSIONS.DISCLOSURE_CREATE,
  PERMISSIONS.DISCLOSURE_SEND,
  PERMISSIONS.DISCLOSURE_ACKNOWLEDGE,

  // TASK
  PERMISSIONS.TASK_VIEW,
  PERMISSIONS.TASK_CREATE,
  PERMISSIONS.TASK_EDIT,
  PERMISSIONS.TASK_DELETE,
  PERMISSIONS.TASK_COMPLETE,
  PERMISSIONS.TASK_ASSIGN_SELF,
  PERMISSIONS.TASK_ASSIGN_ANY,
  PERMISSIONS.TASK_REORDER,
  PERMISSIONS.TASK_AI_GENERATE,

  // MESSAGE
  PERMISSIONS.MESSAGE_VIEW,
  PERMISSIONS.MESSAGE_READ_RECEIPT,
  PERMISSIONS.MESSAGE_SEND,
  PERMISSIONS.MESSAGE_EDIT_OWN,
  PERMISSIONS.MESSAGE_DELETE_OWN,
  PERMISSIONS.MESSAGE_AI_DRAFT,
  PERMISSIONS.MESSAGE_PIN,
  PERMISSIONS.MESSAGE_ARCHIVE,
  PERMISSIONS.MESSAGE_USE_TEMPLATES,
  PERMISSIONS.MESSAGE_APPROVE_BEFORE_SEND,
  PERMISSIONS.MESSAGE_MANAGE_TEMPLATES,

  // DOCUMENT
  PERMISSIONS.DOCUMENT_VIEW,
  PERMISSIONS.DOCUMENT_VERSION_HISTORY,
  PERMISSIONS.DOCUMENT_VIEW_AUDIT_TRAIL,
  PERMISSIONS.DOCUMENT_UPLOAD,
  PERMISSIONS.DOCUMENT_DOWNLOAD,
  PERMISSIONS.DOCUMENT_DELETE_OWN,
  PERMISSIONS.DOCUMENT_REQUEST,
  PERMISSIONS.DOCUMENT_SIGN,
  PERMISSIONS.DOCUMENT_EDIT_METADATA,
  PERMISSIONS.DOCUMENT_REPLACE_VERSION,
  PERMISSIONS.DOCUMENT_SHARE,
  PERMISSIONS.DOCUMENT_REQUEST_SIGNATURE,
  PERMISSIONS.DOCUMENT_MARK_RECEIVED,
  PERMISSIONS.DOCUMENT_MARK_MISSING,
  PERMISSIONS.DOCUMENT_CLASSIFY,
  PERMISSIONS.DOCUMENT_APPROVE,
  PERMISSIONS.DOCUMENT_REJECT,
  PERMISSIONS.DOCUMENT_SET_VISIBILITY,
  PERMISSIONS.DOCUMENT_MANAGE_CHECKLIST,

  // ESIGN
  PERMISSIONS.ESIGN_VIEW_STATUS,
  PERMISSIONS.ESIGN_SEND,
  PERMISSIONS.ESIGN_CANCEL,
  PERMISSIONS.ESIGN_REMIND,
  PERMISSIONS.ESIGN_MANAGE_RECIPIENTS,
  PERMISSIONS.ESIGN_DOWNLOAD_CERTIFICATE,

  // PROPERTY
  PERMISSIONS.PROPERTY_VIEW,
  PERMISSIONS.PROPERTY_VIEW_VALUATION,
  PERMISSIONS.PROPERTY_ADD,
  PERMISSIONS.PROPERTY_EDIT,
  PERMISSIONS.PROPERTY_REMOVE,
  PERMISSIONS.PROPERTY_PHOTO_UPLOAD,
  PERMISSIONS.PROPERTY_AI_ANALYZE,
  PERMISSIONS.PROPERTY_ENRICH_MLS,
  PERMISSIONS.PROPERTY_LINK_MLS,
  PERMISSIONS.PROPERTY_UNLINK_MLS,
  PERMISSIONS.PROPERTY_EDIT_VALUATION,

  // CMA
  PERMISSIONS.CMA_VIEW,
  PERMISSIONS.CMA_CREATE,
  PERMISSIONS.CMA_EDIT,
  PERMISSIONS.CMA_EXPORT,
  PERMISSIONS.CMA_DELETE,

  // LISTING
  PERMISSIONS.LISTING_VIEW,
  PERMISSIONS.LISTING_VIEW_FEEDBACK_SUMMARY,
  PERMISSIONS.LISTING_VIEW_PERFORMANCE,
  PERMISSIONS.LISTING_CREATE,
  PERMISSIONS.LISTING_EDIT,
  PERMISSIONS.LISTING_PUBLISH,
  PERMISSIONS.LISTING_UNPUBLISH,
  PERMISSIONS.LISTING_PAUSE,
  PERMISSIONS.LISTING_MANAGE_PRICE,
  PERMISSIONS.LISTING_MANAGE_DESCRIPTION,
  PERMISSIONS.LISTING_MANAGE_PHOTOS,
  PERMISSIONS.LISTING_EXPORT_MARKETING,
  PERMISSIONS.LISTING_COPY_GENERATE,
  PERMISSIONS.LISTING_UPDATE_MLS_STATUS,
  PERMISSIONS.LISTING_APPROVE_DRAFT,
  PERMISSIONS.LISTING_MANAGE_SHOWING_INSTRUCTIONS,

  // SHOWING
  PERMISSIONS.SHOWING_VIEW,
  PERMISSIONS.SHOWING_FEEDBACK_VIEW,
  PERMISSIONS.SHOWING_VIEW_ACTIVITY_REPORT,
  PERMISSIONS.SHOWING_VIEW_BUYER_IDENTITY,
  PERMISSIONS.SHOWING_REQUEST,
  PERMISSIONS.SHOWING_SCHEDULE,
  PERMISSIONS.SHOWING_CANCEL,
  PERMISSIONS.SHOWING_REQUEST_FEEDBACK,
  PERMISSIONS.SHOWING_AUTO_APPROVE_TOGGLE,

  // OFFER
  PERMISSIONS.OFFER_VIEW,
  PERMISSIONS.OFFER_VIEW_ANALYSIS_DETAILS,
  PERMISSIONS.OFFER_SUBMIT,
  PERMISSIONS.OFFER_EDIT,
  PERMISSIONS.OFFER_WITHDRAW,
  PERMISSIONS.OFFER_EXPIRE,
  PERMISSIONS.OFFER_REOPEN,
  PERMISSIONS.OFFER_ACCEPT,
  PERMISSIONS.OFFER_REJECT,
  PERMISSIONS.OFFER_COUNTER,
  PERMISSIONS.OFFER_COMPARE,
  PERMISSIONS.OFFER_AI_ANALYZE,
  PERMISSIONS.OFFER_SHARE,
  PERMISSIONS.OFFER_MANAGE_COUNTER_CHAIN,
  PERMISSIONS.OFFER_PRESENT,
  PERMISSIONS.OFFER_REQUEST_HIGHEST_BEST,
  PERMISSIONS.OFFER_CREATE_NET_SHEET,
  PERMISSIONS.OFFER_APPROVE_FOR_SEND,
  PERMISSIONS.OFFER_LOCK,
  PERMISSIONS.OFFER_UNLOCK,

  // APPRAISAL
  PERMISSIONS.APPRAISAL_VIEW_RESULT,
  PERMISSIONS.APPRAISAL_VIEW_REPORT,
  PERMISSIONS.APPRAISAL_COORDINATE_ACCESS,
  PERMISSIONS.APPRAISAL_SUBMIT_ROV,

  // EVENT
  PERMISSIONS.EVENT_VIEW,
  PERMISSIONS.EVENT_VIEW_AVAILABILITY,
  PERMISSIONS.EVENT_CREATE,
  PERMISSIONS.EVENT_EDIT,
  PERMISSIONS.EVENT_DELETE,
  PERMISSIONS.EVENT_RESPOND,
  PERMISSIONS.EVENT_RESCHEDULE,
  PERMISSIONS.EVENT_MANAGE_ATTENDEES,
  PERMISSIONS.EVENT_SCHEDULE_FOR_OTHERS,
  PERMISSIONS.EVENT_CALENDAR_SYNC,
  PERMISSIONS.EVENT_LINK_TO_STAGE,
  PERMISSIONS.EVENT_UNLINK_FROM_STAGE,

  // PIPELINE
  PERMISSIONS.PIPELINE_VIEW_OWN,
  PERMISSIONS.PIPELINE_FILTER,
  PERMISSIONS.PIPELINE_BULK_ACTION,
  PERMISSIONS.PIPELINE_EXPORT,

  // AI
  PERMISSIONS.AI_GENERATE_TASKS,
  PERMISSIONS.AI_DRAFT_COMMUNICATION,
  PERMISSIONS.AI_GENERATE_LISTING,
  PERMISSIONS.AI_GENERATE_CMA,
  PERMISSIONS.AI_ANALYZE_OFFER,
  PERMISSIONS.AI_SCORE_LEAD,
  PERMISSIONS.AI_NEGOTIATION_COPILOT,
  PERMISSIONS.AI_APPROVE_OUTPUT,

  // LENDING
  PERMISSIONS.LENDING_VIEW_STATUS,
  PERMISSIONS.LENDING_VIEW_MILESTONES,
  PERMISSIONS.LENDING_VIEW_DISCLOSURES,
  PERMISSIONS.LENDING_VIEW_SENSITIVE_LOAN_DATA,
  PERMISSIONS.LENDING_SYNC,
  PERMISSIONS.LENDING_RESEND_DISCLOSURES,
  PERMISSIONS.LENDING_MARK_PREAPPROVED,
  PERMISSIONS.LENDING_MARK_CLEARED,
  PERMISSIONS.LENDING_REQUEST_PREAPPROVAL,
  PERMISSIONS.LENDING_UPDATE_STATUS_MANUAL,

  // TITLE
  PERMISSIONS.TITLE_VIEW_COMMITMENT,
  PERMISSIONS.TITLE_VIEW_INSURANCE_POLICY,
  PERMISSIONS.TITLE_FLAG_EXCEPTION,
  PERMISSIONS.TITLE_CONFIRM_CLEAR,

  // CLOSING
  PERMISSIONS.CLOSING_VIEW_WIRE_INSTRUCTIONS,
  PERMISSIONS.CLOSING_SCHEDULE,
  PERMISSIONS.CLOSING_CONFIRM_FUNDS,
  PERMISSIONS.CLOSING_APPROVE_ALTA,
  PERMISSIONS.CLOSING_COMPLETE,

  // POST-CLOSE
  PERMISSIONS.POST_CLOSE_CONFIRM_RECORDING,
  PERMISSIONS.POST_CLOSE_DELIVER_DOCUMENTS,
  PERMISSIONS.POST_CLOSE_TRACK_TITLE_POLICY,
  PERMISSIONS.POST_CLOSE_SUBMIT_COMPLIANCE_FILE,

  // FASTPASS
  PERMISSIONS.FASTPASS_VIEW,
  PERMISSIONS.FASTPASS_ENROLL,
  PERMISSIONS.FASTPASS_MANAGE,

  // PORTAL — agents configure what their clients see
  PERMISSIONS.PORTAL_VIEW,
  PERMISSIONS.PORTAL_MANAGE_SECTIONS,
  PERMISSIONS.PORTAL_SHOW_STAGE_PROGRESS,
  PERMISSIONS.PORTAL_SHOW_DOCUMENTS,
  PERMISSIONS.PORTAL_SHOW_TASKS,
  PERMISSIONS.PORTAL_SHOW_MESSAGES,
  PERMISSIONS.PORTAL_SHOW_OFFERS,

  // NOTIFICATION
  PERMISSIONS.NOTIFICATION_RECEIVE,
  PERMISSIONS.NOTIFICATION_TRIGGER_MANUAL,
  PERMISSIONS.NOTIFICATION_MUTE_DEAL,
  PERMISSIONS.NOTIFICATION_MUTE_USER,
  PERMISSIONS.NOTIFICATION_MANAGE,
  PERMISSIONS.NOTIFICATION_MANAGE_TEMPLATES,

  // AUTOMATION — view only; agents don't build automations
  PERMISSIONS.AUTOMATION_VIEW,

  // BILLING
  PERMISSIONS.BILLING_VIEW,
  PERMISSIONS.BILLING_VIEW_TRANSACTION_HISTORY,
  PERMISSIONS.BILLING_CHARGE,
  PERMISSIONS.BILLING_DOWNLOAD_INVOICE,
  PERMISSIONS.BILLING_APPLY_PROMOTION,

  // ANALYTICS
  PERMISSIONS.ANALYTICS_VIEW_OWN,
  PERMISSIONS.ANALYTICS_VIEW_DEAL_HEALTH,
  PERMISSIONS.ANALYTICS_VIEW_CONVERSION,
  PERMISSIONS.ANALYTICS_VIEW_STAGE_PERFORMANCE,

  // REPORT
  PERMISSIONS.REPORT_VIEW,
  PERMISSIONS.REPORT_CREATE,
  PERMISSIONS.REPORT_EXPORT,

  // DASHBOARD
  PERMISSIONS.DASHBOARD_VIEW,
  PERMISSIONS.DASHBOARD_CUSTOMIZE,

  // SEARCH
  PERMISSIONS.SEARCH_GLOBAL,
  PERMISSIONS.SEARCH_DEALS,
  PERMISSIONS.SEARCH_DOCUMENTS,
  PERMISSIONS.SEARCH_MESSAGES,

  // EXPORT
  PERMISSIONS.EXPORT_DEALS,
  PERMISSIONS.EXPORT_DOCUMENTS,
  PERMISSIONS.EXPORT_MESSAGES,

  // TEMPLATE
  PERMISSIONS.TEMPLATE_VIEW,
  PERMISSIONS.TEMPLATE_CREATE,
  PERMISSIONS.TEMPLATE_EDIT,
  PERMISSIONS.TEMPLATE_DELETE,
  PERMISSIONS.TEMPLATE_USE,
  PERMISSIONS.TEMPLATE_ASSIGN,
  PERMISSIONS.TEMPLATE_PUBLISH,
];

// ─────────────────────────────────────────────────────────────────────────────
// TRANSACTION COORDINATOR (TC)
//
// Administrative role: manages paperwork, deadlines, scheduling, and third-party
// coordination from contract execution through post-close.
//
// Legal wall: TCs CANNOT negotiate, advise on price/strategy, change MLS status,
// or communicate with clients unless the agent explicitly delegates that access
// via deal.configure_tc_access. This group defines the baseline — per-deal
// delegation (controlled by the agent) can expand it for specific deals.
// ─────────────────────────────────────────────────────────────────────────────
const TC_PERMISSIONS: Permission[] = [

  // DEAL — view only; scoped to assigned deals at the data layer
  PERMISSIONS.DEAL_VIEW,
  PERMISSIONS.DEAL_VIEW_FINANCIALS,    // needs to verify fee/commission accuracy on ALTA

  // STAGE — TCs track requirements, check off items, and roll back stages when deals fall out
  PERMISSIONS.STAGE_VIEW_REQUIREMENTS,
  PERMISSIONS.STAGE_VIEW_HISTORY,
  PERMISSIONS.STAGE_COMPLETE_REQUIREMENT,
  PERMISSIONS.STAGE_ROLLBACK,

  // DEAL — TCs can mark a deal fallen through; cannot reactivate (agent/admin decision)
  PERMISSIONS.DEAL_MARK_FALLEN_THROUGH,

  // CONTINGENCY — core TC responsibility
  PERMISSIONS.CONTINGENCY_VIEW,
  PERMISSIONS.CONTINGENCY_TRACK,
  PERMISSIONS.CONTINGENCY_REMOVE,      // TC executes removal after agent instructs
  PERMISSIONS.CONTINGENCY_EXTEND,      // TC processes extension addenda

  // EARNEST MONEY — TC confirms deposit was received
  PERMISSIONS.EARNEST_MONEY_VIEW_STATUS,
  PERMISSIONS.EARNEST_MONEY_CONFIRM_RECEIPT,

  // DISCLOSURE — TC prepares and delivers disclosure packages
  PERMISSIONS.DISCLOSURE_VIEW,
  PERMISSIONS.DISCLOSURE_VIEW_STATUS,
  PERMISSIONS.DISCLOSURE_CREATE,
  PERMISSIONS.DISCLOSURE_SEND,

  // TASK — TCs manage the transaction task board
  PERMISSIONS.TASK_VIEW,
  PERMISSIONS.TASK_CREATE,
  PERMISSIONS.TASK_EDIT,
  PERMISSIONS.TASK_COMPLETE,
  PERMISSIONS.TASK_ASSIGN_SELF,
  PERMISSIONS.TASK_ASSIGN_ANY,
  PERMISSIONS.TASK_REORDER,
  PERMISSIONS.TASK_AI_GENERATE,

  // MESSAGE — TCs communicate with lender, title, and third parties
  PERMISSIONS.MESSAGE_VIEW,
  PERMISSIONS.MESSAGE_READ_RECEIPT,
  PERMISSIONS.MESSAGE_SEND,
  PERMISSIONS.MESSAGE_EDIT_OWN,
  PERMISSIONS.MESSAGE_DELETE_OWN,
  PERMISSIONS.MESSAGE_AI_DRAFT,
  PERMISSIONS.MESSAGE_PIN,
  PERMISSIONS.MESSAGE_ARCHIVE,
  PERMISSIONS.MESSAGE_USE_TEMPLATES,
  PERMISSIONS.MESSAGE_MANAGE_TEMPLATES,

  // DOCUMENT — TCs are the document managers of the transaction
  PERMISSIONS.DOCUMENT_VIEW,
  PERMISSIONS.DOCUMENT_VERSION_HISTORY,
  PERMISSIONS.DOCUMENT_VIEW_AUDIT_TRAIL,
  PERMISSIONS.DOCUMENT_UPLOAD,
  PERMISSIONS.DOCUMENT_DOWNLOAD,
  PERMISSIONS.DOCUMENT_DELETE_OWN,
  PERMISSIONS.DOCUMENT_REQUEST,
  PERMISSIONS.DOCUMENT_EDIT_METADATA,
  PERMISSIONS.DOCUMENT_REPLACE_VERSION,
  PERMISSIONS.DOCUMENT_SHARE,
  PERMISSIONS.DOCUMENT_REQUEST_SIGNATURE,
  PERMISSIONS.DOCUMENT_MARK_RECEIVED,
  PERMISSIONS.DOCUMENT_MARK_MISSING,
  PERMISSIONS.DOCUMENT_CLASSIFY,
  PERMISSIONS.DOCUMENT_VIEW_AUDIT_TRAIL,
  PERMISSIONS.DOCUMENT_SET_VISIBILITY,
  PERMISSIONS.DOCUMENT_MANAGE_CHECKLIST,
  PERMISSIONS.DOCUMENT_APPROVE,
  PERMISSIONS.DOCUMENT_REJECT,

  // ESIGN — TCs send and manage signature envelopes
  PERMISSIONS.ESIGN_VIEW_STATUS,
  PERMISSIONS.ESIGN_SEND,
  PERMISSIONS.ESIGN_CANCEL,
  PERMISSIONS.ESIGN_REMIND,
  PERMISSIONS.ESIGN_MANAGE_RECIPIENTS,
  PERMISSIONS.ESIGN_DOWNLOAD_CERTIFICATE,

  // SHOWING — TCs coordinate access scheduling
  PERMISSIONS.SHOWING_VIEW,
  PERMISSIONS.SHOWING_SCHEDULE,
  PERMISSIONS.SHOWING_VIEW_ACTIVITY_REPORT,
  PERMISSIONS.SHOWING_REQUEST_FEEDBACK,

  // OFFER — view only; TC cannot negotiate
  PERMISSIONS.OFFER_VIEW,

  // APPRAISAL — TC coordinates property access
  PERMISSIONS.APPRAISAL_VIEW_RESULT,
  PERMISSIONS.APPRAISAL_COORDINATE_ACCESS,

  // EVENT — TCs schedule all transaction events
  PERMISSIONS.EVENT_VIEW,
  PERMISSIONS.EVENT_VIEW_AVAILABILITY,
  PERMISSIONS.EVENT_CREATE,
  PERMISSIONS.EVENT_EDIT,
  PERMISSIONS.EVENT_RESPOND,
  PERMISSIONS.EVENT_RESCHEDULE,
  PERMISSIONS.EVENT_MANAGE_ATTENDEES,
  PERMISSIONS.EVENT_SCHEDULE_FOR_OTHERS,
  PERMISSIONS.EVENT_LINK_TO_STAGE,
  PERMISSIONS.EVENT_UNLINK_FROM_STAGE,

  // PIPELINE — only their assigned transactions
  PERMISSIONS.PIPELINE_VIEW_OWN,
  PERMISSIONS.PIPELINE_FILTER,

  // LENDING — track milestones; cannot take lending actions
  PERMISSIONS.LENDING_VIEW_STATUS,
  PERMISSIONS.LENDING_VIEW_MILESTONES,
  PERMISSIONS.LENDING_VIEW_DISCLOSURES,

  // TITLE — review commitment and flag issues for agent
  PERMISSIONS.TITLE_VIEW_COMMITMENT,
  PERMISSIONS.TITLE_FLAG_EXCEPTION,
  PERMISSIONS.TITLE_CONFIRM_CLEAR,

  // CLOSING — TCs prep, schedule, verify funds, confirm ALTA accuracy, close file
  PERMISSIONS.CLOSING_VIEW_WIRE_INSTRUCTIONS,
  PERMISSIONS.CLOSING_SCHEDULE,
  PERMISSIONS.CLOSING_CONFIRM_FUNDS,
  PERMISSIONS.CLOSING_APPROVE_ALTA,
  PERMISSIONS.CLOSING_COMPLETE,

  // POST-CLOSE — TCs handle all post-close follow-through
  PERMISSIONS.POST_CLOSE_CONFIRM_RECORDING,
  PERMISSIONS.POST_CLOSE_DELIVER_DOCUMENTS,
  PERMISSIONS.POST_CLOSE_TRACK_TITLE_POLICY,
  PERMISSIONS.POST_CLOSE_SUBMIT_COMPLIANCE_FILE,

  // NOTIFICATION
  PERMISSIONS.NOTIFICATION_RECEIVE,
  PERMISSIONS.NOTIFICATION_TRIGGER_MANUAL,
  PERMISSIONS.NOTIFICATION_MUTE_DEAL,
  PERMISSIONS.NOTIFICATION_MANAGE,
  PERMISSIONS.NOTIFICATION_MANAGE_TEMPLATES,

  // AUTOMATION — view only
  PERMISSIONS.AUTOMATION_VIEW,

  // BILLING — view status only; TC doesn't manage payments
  PERMISSIONS.BILLING_VIEW,

  // ANALYTICS — own performance only
  PERMISSIONS.ANALYTICS_VIEW_OWN,

  // SEARCH
  PERMISSIONS.SEARCH_DEALS,
  PERMISSIONS.SEARCH_DOCUMENTS,
  PERMISSIONS.SEARCH_MESSAGES,

  // DASHBOARD
  PERMISSIONS.DASHBOARD_VIEW,

  // TEMPLATE
  PERMISSIONS.TEMPLATE_VIEW,
  PERMISSIONS.TEMPLATE_CREATE,
  PERMISSIONS.TEMPLATE_EDIT,
  PERMISSIONS.TEMPLATE_USE,
  PERMISSIONS.TEMPLATE_ASSIGN,

  // PORTAL — TC can view portal to coordinate what clients see
  PERMISSIONS.PORTAL_VIEW,
];

// ─────────────────────────────────────────────────────────────────────────────
// ADMIN
// All agent permissions plus system-wide visibility, overrides, infrastructure
// configuration, and the full user / bundle / role / permission management stack.
// ─────────────────────────────────────────────────────────────────────────────
const ADMIN_PERMISSIONS: Permission[] = [
  ...AGENT_PERMISSIONS,

  // DEAL — system-wide access + destructive actions
  PERMISSIONS.DEAL_VIEW_ALL,
  PERMISSIONS.DEAL_DELETE,
  PERMISSIONS.DEAL_ADVANCE_STAGE_OVERRIDE,
  PERMISSIONS.DEAL_OVERRIDE_PERMISSIONS,

  // STAGE — full engine control
  PERMISSIONS.STAGE_ROLLBACK,
  PERMISSIONS.STAGE_LOCK,
  PERMISSIONS.STAGE_UNLOCK,
  PERMISSIONS.STAGE_CONFIGURE_TRIGGERS,
  PERMISSIONS.STAGE_OVERRIDE_REQUIREMENTS,

  // EARNEST MONEY — admin can release or resolve disputes
  PERMISSIONS.EARNEST_MONEY_RELEASE,
  PERMISSIONS.EARNEST_MONEY_DISPUTE,

  // MESSAGE — moderation + external comms
  PERMISSIONS.MESSAGE_DELETE_ANY,
  PERMISSIONS.MESSAGE_EXPORT,
  PERMISSIONS.MESSAGE_SEND_EXTERNAL,

  // DOCUMENT — admin-level document control
  PERMISSIONS.DOCUMENT_DELETE_ANY,
  PERMISSIONS.DOCUMENT_RESTORE_VERSION,
  PERMISSIONS.DOCUMENT_LOCK,
  PERMISSIONS.DOCUMENT_UNLOCK,

  // PIPELINE — cross-agent visibility
  PERMISSIONS.PIPELINE_VIEW_ALL,

  // LENDING — provider + infrastructure management
  PERMISSIONS.LENDING_CONNECT_PROVIDER,
  PERMISSIONS.LENDING_DISCONNECT_PROVIDER,
  PERMISSIONS.LENDING_MANAGE_WEBHOOKS,
  PERMISSIONS.LENDING_OVERRIDE_STATUS,

  // TITLE — admin can view title insurance policy
  PERMISSIONS.TITLE_VIEW_INSURANCE_POLICY,

  // FASTPASS — fee waiver
  PERMISSIONS.FASTPASS_WAIVE_FEE,

  // NOTIFICATION — broadcast + push to any user
  PERMISSIONS.NOTIFICATION_SEND_ANY,
  PERMISSIONS.NOTIFICATION_BROADCAST,

  // AUTOMATION — full workflow control
  PERMISSIONS.AUTOMATION_CREATE,
  PERMISSIONS.AUTOMATION_EDIT,
  PERMISSIONS.AUTOMATION_RUN,
  PERMISSIONS.AUTOMATION_DISABLE,

  // PERMISSION management
  PERMISSIONS.PERMISSION_VIEW,
  PERMISSIONS.PERMISSION_CREATE,
  PERMISSIONS.PERMISSION_EDIT,
  PERMISSIONS.PERMISSION_ASSIGN,

  // BUNDLE management
  PERMISSIONS.BUNDLE_CREATE,
  PERMISSIONS.BUNDLE_EDIT,
  PERMISSIONS.BUNDLE_DELETE,
  PERMISSIONS.BUNDLE_ASSIGN,

  // ROLE management
  PERMISSIONS.ROLE_CREATE,
  PERMISSIONS.ROLE_EDIT,
  PERMISSIONS.ROLE_DELETE,
  PERMISSIONS.ROLE_ASSIGN,

  // USER lifecycle
  PERMISSIONS.USER_INVITE,
  PERMISSIONS.USER_DEACTIVATE,
  PERMISSIONS.USER_REACTIVATE,
  PERMISSIONS.USER_RESET_PASSWORD,
  PERMISSIONS.USER_ASSIGN_ROLE,

  // BILLING — refunds, waives, exports
  PERMISSIONS.BILLING_REFUND,
  PERMISSIONS.BILLING_WAIVE,
  PERMISSIONS.BILLING_RETRY_PAYMENT,
  PERMISSIONS.BILLING_EXPORT_TRANSACTIONS,

  // ANALYTICS — org-wide + team + AI metrics
  PERMISSIONS.ANALYTICS_VIEW_ALL,
  PERMISSIONS.ANALYTICS_VIEW_TEAM,
  PERMISSIONS.ANALYTICS_AI_METRICS,
  PERMISSIONS.ANALYTICS_EXPORT,

  // DASHBOARD — sharing
  PERMISSIONS.DASHBOARD_SHARE,

  // AUDIT
  PERMISSIONS.AUDIT_VIEW,
  PERMISSIONS.AUDIT_FILTER,
  PERMISSIONS.AUDIT_EXPORT,

  // SECURITY
  PERMISSIONS.SECURITY_VIEW_SESSIONS,
  PERMISSIONS.SECURITY_REVOKE_SESSIONS,
  PERMISSIONS.SECURITY_MANAGE_MFA,

  // COMPLIANCE
  PERMISSIONS.COMPLIANCE_VIEW_FLAGS,
  PERMISSIONS.COMPLIANCE_RESOLVE_FLAGS,
  PERMISSIONS.COMPLIANCE_PLACE_LEGAL_HOLD,
  PERMISSIONS.COMPLIANCE_MANAGE_RETENTION,

  // IMPORT
  PERMISSIONS.IMPORT_DEALS,
  PERMISSIONS.IMPORT_CONTACTS,

  // ADMIN system config
  PERMISSIONS.ADMIN_CONFIGURE_SYSTEM,
  PERMISSIONS.ADMIN_MANAGE_FEES,
  PERMISSIONS.ADMIN_MANAGE_PROMOTIONS,
  PERMISSIONS.ADMIN_IMPERSONATE,
];

// ─────────────────────────────────────────────────────────────────────────────
// GROUPS registry
// ─────────────────────────────────────────────────────────────────────────────
export const GROUPS: Record<GroupId, PermissionGroup> = {
  buyer: {
    id: 'buyer',
    name: 'Buyer',
    description: 'Client actively purchasing a property',
    permissions: BUYER_PERMISSIONS,
  },

  seller: {
    id: 'seller',
    name: 'Seller',
    description: 'Client actively selling a property',
    permissions: SELLER_PERMISSIONS,
  },

  agent: {
    id: 'agent',
    name: 'Agent',
    description: 'Licensed real estate agent managing transactions end-to-end',
    permissions: AGENT_PERMISSIONS,
  },

  tc: {
    id: 'tc',
    name: 'Transaction Coordinator',
    description: 'Administrative coordinator managing paperwork, deadlines, and third-party communication from contract to post-close',
    permissions: TC_PERMISSIONS,
  },

  admin: {
    id: 'admin',
    name: 'Admin',
    description: 'Administrator with full system access, override capabilities, and infrastructure control',
    permissions: ADMIN_PERMISSIONS,
  },
};
